# Generated by Django 4.1.13 on 2024-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Trainer/')),
                ('facebook', models.CharField(max_length=70)),
                ('instagram', models.CharField(max_length=70)),
                ('twitter', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
