# Generated by Django 4.1.13 on 2024-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0002_trainer_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='twitter',
        ),
        migrations.AddField(
            model_name='trainer',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
