# Generated by Django 4.1.13 on 2024-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0003_remove_trainer_facebook_remove_trainer_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='Article/image')),
                ('create_data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
