# Generated by Django 4.1.13 on 2024-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0006_jamoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
