# Generated by Django 4.1.13 on 2024-05-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0008_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_data',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
