# Generated by Django 4.1.13 on 2024-05-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0009_rename_description_article_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='create_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
