# Generated by Django 4.1.13 on 2024-05-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0011_portfol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfol',
        ),
    ]
