# Generated by Django 4.1.13 on 2024-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0013_remove_article_author_alter_article_id_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='description',
        ),
        migrations.AddField(
            model_name='trainer',
            name='facebook',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='full_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter',
            field=models.CharField(default=0.0004943153732081067, max_length=70),
            preserve_default=False,
        ),
    ]
