# Generated by Django 4.1.13 on 2024-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0015_port_delete_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='github',
            field=models.CharField(default=0.0004940711462450593, max_length=70),
            preserve_default=False,
        ),
    ]
