# Generated by Django 4.1.13 on 2024-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0017_article_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamoa',
            name='github',
            field=models.CharField(default=0.0004943153732081067, max_length=70),
            preserve_default=False,
        ),
    ]
